#!/usr/bin/env python3
"""Update the version files for a release (mirrors update-version.py of yt-dlp)."""

import argparse
import contextlib
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from devscripts.utils import calculate_version, run_process, write_file


def get_git_head():
    with contextlib.suppress(Exception):
        return run_process('git', 'rev-parse', 'HEAD').stdout.strip()


VERSION_TEMPLATE = '''\
# Autogenerated by devscripts/update-version.py

__version__ = {version!r}

RELEASE_GIT_HEAD = {git_head!r}

VARIANT = None

UPDATE_HINT = None

CHANNEL = {channel!r}

ORIGIN = {origin!r}

_pkg_version = {package_version!r}
'''


def update_pyproject(version):
    path = 'pyproject.toml'
    with open(path, encoding='utf-8') as f:
        content = f.read()
    content = re.sub(
        r'(?m)^version\s*=\s*"[^"]*"', f'version = "{version}"', content, count=1,
    )
    write_file(path, content)
    print(f'Updated: {path}')


def main():
    parser = argparse.ArgumentParser(description='Update the version files')
    parser.add_argument('-c', '--channel', default='stable')
    parser.add_argument('-r', '--origin', default='local')
    parser.add_argument('-o', '--output', default='src/ytdlp_gui/version.py')
    parser.add_argument('version', nargs='?', default=None)
    args = parser.parse_args()

    git_head = get_git_head() or ''
    version = calculate_version(args.version)
    write_file(args.output, VERSION_TEMPLATE.format(
        version=version, git_head=git_head, channel=args.channel, origin=args.origin,
        package_version=version,
    ))
    print(f'Updated: {args.output}')
    update_pyproject(version)
    print(f'version={version} ({args.channel}), head={git_head}')


if __name__ == '__main__':
    main()
