# Autogenerated by devscripts/update-version.py

__version__ = '2026.08.01'

RELEASE_GIT_HEAD = 'bf16326fe1c0d5759815f4edf2ea2c2b21a3edff'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'stable'

ORIGIN = 'vokrob/yt-dlp-gui'

_pkg_version = '2026.08.01'
